openapi: "3.0.2"
info:
  title: MWNZ companies
  version: "1.0"
  description: Your Node.js API should produce a JSON response that aligns with this specification
servers:
  - url: https://api.server.test/v1
paths:
  /companies/{id}:
    get:
      tags:
        - Companies
      parameters:
        - name: id
          description: Company ID
          in: path
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/xml:
              schema:
                $ref: "#/components/schemas/Company"
              examples:
                MWNZ:
                  value:
                    id: 1
                    name: MWNZ
                    description: "..is awesome"
                Other:
                  value:
                    id: 2
                    name: Other
                    description: "....is not"

components:
  schemas:
    Company:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
